In [2]:
import numpy as np

In [3]:
myarr = np.array([[3,6,7,9]],np.int64)

In [4]:
myarr.shape

(1, 4)

In [5]:
zeroes = np.zeros((2,5))

In [6]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
zeroes.dtype

dtype('float64')

In [8]:
rang = np.arange(15)

In [9]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
lspace = np.linspace(1,10,5)

In [11]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

linspace = divede 1 to 10 into equally spaced 5 numbers

In [12]:
emp = np.empty((4,6))

In [13]:
emp2 = np.empty_like(lspace)

In [14]:
emp2

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

empty_like() function returns an array of uninitialized data with the same shape and type as the prototypes passed to it.

In [15]:
ide = np.identity(45)

In [16]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

identity matrix of 45 x 45

In [17]:
arr = np.arange(99)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

arr got reshaped into 3 x 33 matrix but be careful while telling no. of rows and columns

In [19]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

coonversion of mulyidimensional array into 1d array

In [20]:
arr = arr.ravel()

In [21]:
arr.shape

(99,)

axis in numpy array

In [22]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [23]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [24]:
ar.sum(axis=0)

array([12,  8,  9])

In [25]:
ar.sum(axis=1)

array([ 6, 15,  8])

attribute of array

1. transpose of array

In [26]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

2. ar.flat it gives iterator - rowwise hota h 

In [27]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


3. no of dimensions - ndim

In [28]:
ar.ndim

2

In [29]:
ar.size

9

In [30]:
one = np.array([1,3,4,78,2])

In [31]:
one.argmax()

3

In [32]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

argmin() or argmax()... on 2d array : first convert 2D array into 1D array and then works on it

In [33]:
ar.argmin()

8

In [34]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [36]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [37]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [38]:
ar2 = np.array([[2,7,9],[6,8,4],[3,4,5]])

In [39]:
ar2

array([[2, 7, 9],
       [6, 8, 4],
       [3, 4, 5]])

In [40]:
ar + ar2

array([[ 3,  9, 12],
       [10, 13, 10],
       [10,  5,  5]])

In [41]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [44]:
ar.sum()


29

In [45]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [47]:
import sys

In [48]:
py_arr = [1,3,45,6]

In [49]:
np_arr = np.array(py_arr)

To get size of array and how numpy is storage efficient